### PR TITLE
Homework 6 (tests for service)

### PR DESCRIPTION
**Pull request by subtle-byte**
By Maxim Meshkov

image

### CODE REVIEW

**Comment by ilyazamyslov** [comment]
I need to study your " func (s *Suite) TestBadExternalAPIResponse ()". I couldn't test just these sections of the code, but everything is compact here, different cases are briefly considered. Beautiful :)

**Comment by AlexRyzhickov** [comment]
Why you commit "go.sum" ? I think you don't need it. The rest is absolutly great :)

**Comment by AlexRyzhickov** [comment]
Why do you add "go.sum" ? I think you don't need it. The rest is absolutly great :)

**Comment by AlexRyzhickov** [comment]
Why do you add "go.sum" ? I think you don't need it. The rest is absolutely great :)

**Comment by subtle-byte** [comment]
@AlexRyzhickov `go.sum` was in the repository before me and I updated it because `testify v1.3.0`'s `Suite` does not have `ErrorAs` method.

**Comment by pavlov-tony** [comment]
Great work! Keep it up!

**Pull request closed without merging**
